seed: 42

data:
  train_dir: data/train
  val_dir: data/val
  use_hdf5: false
  target_shape: [64, 64, 64]
  batch_size: 4
  num_workers: 16
  weighted_sampler: false
  use_2d: true
  num_slices: 8
  slice_axis: 0
  slice_strategy_train: random
  slice_strategy_val: uniform
  resize_2d: [224, 224]

model:
  name: deit2d  # simple | unet | resunet | vit2d | swin2d | swin3d | deit2d
  in_channels: 1
  num_classes: 2
  timm_name: deit_base_patch16_224.fb_in1k
  pretrained: true
  image_size: 224
  drop_path_rate: 0.2
  attn_drop_rate: 0.1
  dropout: 0.1

training:
  max_epochs: 256
  lr: 5.0e-5
  weight_decay: 0.05
  accelerator: gpu
  devices: [3]
  precision: 16
  loss:
    label_smoothing: 0.1
  optimizer:
    name: AdamW
    betas: [0.9, 0.999]
  class_weights:
    enabled: true
    values: null
  lr_scheduler:
    enabled: true
    name: OneCycleLR
    max_lr: 5.0e-5
    pct_start: 0.1
    anneal_strategy: cos
    interval: step
  early_stopping:
    enabled: true
    monitor: val/auc_epoch
    mode: max
    patience: 12
    min_delta: 0.0

logging:
  wandb:
    enabled: true
    project: alzheimer-baseline
    name: null
    tags: [baseline, 3d-unet]

checkpoint:
  dir: checkpoints/lightning
  monitor: val/auc_epoch
  mode: max
