seed: 42

data:
  format: jpg
  root_dir: data/OASIS/jpg_all
  train_dir: data/OASIS/jpg_all/all
  val_dir: data/OASIS/jpg_all/all
  classes: [normal, alzheimer]
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  split_file: data/OASIS/jpg_all/split_info/folds.json
  fold_index: 0
  image_size: 224
  batch_size: 2
  num_workers: 8
  num_slices: 120
  slice_strategy_train: uniform
  slice_strategy_val: uniform

model:
  name: deit2d
  timm_name: deit_base_patch16_224.fb_in1k
  pretrained: true
  num_classes: 2
  in_channels: 1
  image_size: 224
  drop_path_rate: 0.1
  attn_drop_rate: 0.0
  dropout: 0.2
  slice_attn_hidden_dim: null
  slice_attn_dropout: 0.0
  slice_attn_activation: tanh
  slice_attn_use_layernorm: false

training:
  max_epochs: 128
  lr: 5.0e-5
  weight_decay: 0.05
  optimizer:
    name: AdamW
  loss:
    label_smoothing: 0.1
  accelerator: gpu
  devices: [3]
  precision: 16-mixed
  accumulate_grad_batches: 8
  freeze_backbone: true
  freeze_backbone_ratio: 1.0
  class_weights:
    enabled: true
  lr_scheduler:
    enabled: true
    name: CosineWarmup
    warmup_epochs: 5
    warmup_start_factor: 0.1
    eta_min: 1.0e-6
  early_stopping:
    enabled: true
    monitor: val/auc_epoch
    mode: max
    patience: 16
    min_delta: 0.0

logging:
  wandb:
    enabled: true
    project: alzheimer-baseline
    name: null
    tags: [deit_base_patch16_224, jpg, oasis, stratified_5folds]

checkpoint:
  dir: checkpoints/deit_oasis_5folds
  monitor: val/auc_epoch
  mode: max

output_dir: outputs/train_2d_jpg_oasis_deit
